import{S as u,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const d="48505401-41d9a45057075903c793c7a55",f="https://pixabay.com/api/";function m(n){const o=`${f}?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(e=>{if(!e.ok)throw new Error("Failed to fetch images");return e.json()}).then(e=>{if(e.hits.length===0)throw new Error("No images found");return e.hits})}let l;function p(n){const o=document.querySelector(".card-list");o.innerHTML=n.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </a>
    `).join(""),l?l.refresh():l=new u(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250})}function g(){document.querySelector(".card-list").innerHTML=""}const y=document.querySelector(".search-form");document.querySelector(".card-list");const s=document.createElement("div");s.className="loader";document.body.appendChild(s);y.addEventListener("submit",n=>{n.preventDefault();const o=n.target.elements.query.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query!"});return}g(),s.style.display="block",m(o).then(e=>{if(e.length===0){a.error({title:"Error",message:"Sorry, no images found! Please try again."});return}p(e)}).catch(()=>{a.error({title:"Error",message:"An error occurred while fetching images. Please try again!"})}).finally(()=>{s.style.display="none"})});
//# sourceMappingURL=index.js.map
