import{S as f,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const d="48505401-41d9a45057075903c793c7a55",m="https://pixabay.com/api/";function p(s){const o=`${m}?key=${d}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(e=>{if(!e.ok)throw new Error("Failed to fetch images");return e.json()}).then(e=>{if(e.hits.length===0)throw new Error("No images found");return e.hits})}let a;function y(s){const o=document.querySelector(".card-list");o.innerHTML=s.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </a>
    `).join(""),a?a.refresh():a=new f(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250})}function g(){document.querySelector(".card-list").innerHTML=""}const u=document.querySelector(".search-form");document.querySelector(".card-list");const n=document.createElement("p");n.textContent="Loading...";n.style.display="none";n.style.fontSize="16px";n.style.fontWeight="bold";n.style.textAlign="center";n.style.marginTop="10px";u.insertAdjacentElement("afterend",n);u.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements.query.value.trim();if(!o){l.warning({title:"Warning",message:"Please enter a search query!"});return}g(),n.style.display="block",p(o).then(e=>{if(e.length===0){l.error({title:"Error",message:"Sorry, no images found! Please try again."});return}y(e)}).catch(()=>{l.error({title:"Error",message:"An error occurred while fetching images. Please try again!"})}).finally(()=>{n.style.display="none"})});
//# sourceMappingURL=index.js.map
